apiVersion: V1
kind: Namespace
metadata:
   name: roboshop
   labels:
      environment: Dev
      project: roboshop
      purpose: poc 

#kubectl apply -f 01-namespace.yaml
#kubectl get namespace
#kubectl descripe namespace <name> -o yaml

