apiVersion: v1
kind: Pod
metdata: 
  name: annotations
  labels:
    project: roboshop
  annotations:
    imageregistry: "https://hub.docker.com/"
    jenkins-build-url: "https://jenkins.joindevops.com/build/roboshop/job/2"