apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
    project: roboshop
    environment: dev
spec:
  type: NodePort
  selector:
    project: roboshop
    component: frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port
      nodePort: 30007
# ---
# apiVersion: v1
# kind: Pod 
# metadata: 
#   name: nginx
#   labels:
#      project: roboshop
#      environment: Dev
#      component: frontend
#      tier: frontend
# spec: 
#   containers:
#   - name: nginx
#     image: nginx