apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    project: roboshop
    environment: dev
spec:
  type: LoadBalancer
  selector:
    project: roboshop
    component: frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80 #container port
      nodePort: 30008
