apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    project: roboshop
    tier: frontend
    component: frontend
spec:
  replicas: 10
  selector:
    matchLabels:
      project: roboshop
      tier: frontend
      component: frontend
  template:
    metadata:
      labels:
       project: roboshop
       tier: frontend
       component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
